<oval-def:definition xmlns:oval-def="http://oval.mitre.org/XMLSchema/oval-definitions-5" class="patch" id="oval:com.altx-soft.nix:def:93860" version="0">
  <oval-def:metadata>
    <oval-def:title>DSA-4363-1 -- python-django -- security update</oval-def:title>
    <oval-def:affected family="unix">
      <oval-def:platform>Debian 9</oval-def:platform>
      <oval-def:product>python-django</oval-def:product>
    </oval-def:affected>
    <oval-def:reference ref_id="DSA-4363-1" ref_url="https://www.debian.org/security/dsa-4363" source="VENDOR" />
    <oval-def:reference ref_id="CVE-2019-3498" ref_url="http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-3498" source="CVE" />
    <oval-def:description>It was discovered that malformed URLs could spoof the content of the default 404 page of Django, a Python web development framework.</oval-def:description>
    <oval-def:oval_repository>
      <oval-def:dates>
        <oval-def:submitted date="2019-01-15T10:02:18">
          <oval-def:contributor organization="ALTX-SOFT">Alexandr Ruchkin</oval-def:contributor>
        </oval-def:submitted>
      </oval-def:dates>
      <oval-def:status>INITIAL SUBMISSION</oval-def:status>
    </oval-def:oval_repository>
  </oval-def:metadata>
  <oval-def:criteria>
    <oval-def:extend_definition comment="Debian 9 is installed" definition_ref="oval:org.cisecurity:def:2515" />
    <oval-def:criterion comment="python-django is earlier than 1:1.10.7-2+deb9u4" test_ref="oval:ru.altx-soft.nix:tst:180264" />
  </oval-def:criteria>
</oval-def:definition>
